version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    networks:
      - network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - "5432"
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8000:8000"
    volumes:
      - .:/task_manager
    command: uvicorn task_manager.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
